routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get("/login","DiscordRedirectController")->name("login");
Route::get("/login/discord-callback", "DiscordLoginController@login");
Route::get("/logout","DiscordLoginController@logout");

Route::resource("categories.resources","ResourceController")
    ->middleware(["auth",\App\Http\Middleware\IsAdmin::class . ":" . \App\Enums\DiscordPermissions::MANAGE_WEBHOOKS]);

Route::resource("categories","ResourceCategoryController")
    ->middleware(["auth",\App\Http\Middleware\IsAdmin::class . ":" . \App\Enums\DiscordPermissions::MANAGE_WEBHOOKS]);

app/ResourceCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ResourceCategory extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    //
    protected $fillable = [
        "title","icon","description"
    ];

    public function resources()
    {
        return $this->hasMany(Resource::class,"category_id");
    }
}

app/Http/Controllers/ResourceCategoryController.php
<?php

namespace App\Http\Controllers;

use App\ResourceCategory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class ResourceCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("resource_category.index")->withCategories(ResourceCategory::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("resource_category.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'icon' => 'required',
            'description' => 'required',
        ]);

        ResourceCategory::create($request->all());

        return $this->redirectToIndexForSuccess('New category has been added!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $resourceCategory = ResourceCategory::find($id);

        if(null === $resourceCategory)
            return abort(404);

        return view("resource_category.edit")->withCategory($resourceCategory);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request,int $id)
    {
        $request->validate([
            'title' => 'required',
            'icon' => 'required',
            'description' => 'required',
        ]);

        ResourceCategory::findOrFail($id)
            ->fill($request->toArray())
            ->update();

        return $this->redirectToIndexForSuccess('Your category has been updated.');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(int $id)
    {
        ResourceCategory::findOrFail($id)->delete();

        return $this->redirectToIndexForSuccess('Your category has been deleted.');
    }

    /**
     * Returns a consistent redirect response for a successful action.
     * @param string $message
     * @return \Illuminate\Http\RedirectResponse
     */
    private function redirectToIndexForSuccess(string $message): RedirectResponse
    {
        return Redirect::to(route('categories.index'))->with('success',$message);
    }
}

resources/views/resource_category/resource/create.blade.php
@extends('resource_category/resource/resource_template')

@section('title','Add Resource')

@section('other-content')
    <h1>Add a new resource</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            There was a problem adding this resource.
        </div>
    @endif

    <form action="{{ route("categories.resources.store", $category->id) }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}

        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" class="form-control @error('title')is-invalid"@enderror" id="title"
            placeholder="" required>
            @error('title')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>

        <div class="form-group">
            <label for="bannerImageFileInput">Banner Image</label>
            <input type="file" name="banner_image" class="form-control-file" id="bannerImageFileInput">
        </div>

        <div class="form-group">
            <label for="title">Action</label>
            <input type="text" name="action" class="form-control @error('action')is-invalid"@enderror" id="action"
            placeholder="" required>
            <small class="form-text text-muted">The full link to the resource (i.e. https://dobercorgi.info/).</small>
            @error('action')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>

        <div class="form-group">
            <label class="form-check-label" for="content">Content</label>
            <textarea class="form-control @error('content')is-invalid" @enderror rows="5" name="content"
                      id="content"></textarea>
            <small class="form-text text-muted">A description of what the resource is for.</small>
            @error('content')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/resource_category/resource/edit.blade.php
@extends('resource_category/resource/resource_template')

@section('title','Edit Resource')

@section('other-content')
    <h1>Editing Resource</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            There was a problem adding this resource.
        </div>
    @endif

    @if($resource->file_key)
        <h2>Existing Banner</h2>
        <img class="img-thumbnail" alt="Current banner image" src="{{ Storage::url($resource->file_key) }}"/>
    @endif

    <form action="{{ route("categories.resources.update", [$category->id, $resource->id]) }}" method="POST"
          enctype="multipart/form-data">
        {{ csrf_field() }}
        @method('PUT')

        <div class="form-group">
            <label for="bannerImageFileInput">Banner Image</label>
            <input type="file" name="banner_image" class="form-control-file" id="bannerImageFileInput">
            <small class="form-text text-muted">Leave this empty to keep the previous image.</small>
        </div>

        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" class="form-control @error('title')is-invalid"@enderror" id="title"
            placeholder="" value="{{ $resource->title }}" required>
            @error('title')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>


        <div class="form-group">
            <label for="title">Action</label>
            <input type="text" name="action" class="form-control @error('action')is-invalid"@enderror" id="action"
            placeholder="" value="{{ $resource->action }}" required>
            <small class="form-text text-muted">The full link to the resource (i.e. https://dobercorgi.info/).</small>
            @error('action')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>

        <div class="form-group">
            <label class="form-check-label" for="content">Content</label>
            <textarea class="form-control @error('content')is-invalid" @enderror rows="5" name="content"
                      id="content">{{ $resource->content }}</textarea>
            <small class="form-text text-muted">A description of what the resource is for.</small>
            @error('content')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/resource_category/resource/index.blade.php
@extends('resource_category/resource/resource_template')
@section('title','Resources')

@section('other-content')
    <h1>Resources</h1>
    @if(session("success"))
        <p class="alert alert-success">{{ session("success") }} <a href="#" class="close" data-dismiss="alert"
                                                                   aria-label="close">&times;</a></p>
    @endif

    <a href="{{ route("categories.resources.create",$category->id) }}" class="btn btn-primary mb-3">Add Resource</a>
    <div class="table-responsive">
        <table class="table">
            <tr class="thead-light">
                <th>Title</th>
                <th>Content</th>
                <th>Action</th>
                <th>Image?</th>
                <th>Actions</th>
            </tr>

            @foreach($resources as $resource)
                <tr>
                    <td>{{ $resource->title }}</td>
                    <td>{{ $resource->content }}</td>
                    <td><a href="{{ $resource->action }}">{{ $resource->action }}</a></td>
                    <td>{{ empty($resource->file_key) ? "No" : "Yes" }}</td>
                    <td class="d-flex">
                        <a href="{{ route("categories.resources.edit",[$category->id, $resource->id]) }}"
                           class="btn btn-outline-primary mr-2">Edit</a>

                        <form action="{{ route("categories.resources.destroy",[$category->id, $resource->id]) }}"
                              method="POST">
                            {{ csrf_field() }}
                            @method('DELETE')
                            <button class="btn btn-outline-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection

resources/views/resource_category/resource/resource_template.blade.php
@extends('layouts/app')
@section('title','Resources')

@section('content')
    <h1><span style="font-family: 'Material Icons';">{{ $category->icon }}</span> Category: {{ $category->title }}</h1>
    <p>Description: {{ $category->description }}</p>
    <hr/>

    @yield('other-content')
@endsection