routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::get("/login","DiscordRedirectController")->name("login");
Route::get("/login/discord-callback", "DiscordLoginController@login");
Route::get("/logout","DiscordLoginController@logout");

Route::resource("categories.resources","ResourceController")
    ->middleware(["auth",\App\Http\Middleware\IsAdmin::class . ":" . \App\Enums\DiscordPermissions::MANAGE_WEBHOOKS]);

Route::resource("categories","ResourceCategoryController")
    ->middleware(["auth",\App\Http\Middleware\IsAdmin::class . ":" . \App\Enums\DiscordPermissions::MANAGE_WEBHOOKS]);

app/ResourceCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ResourceCategory extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    //
    protected $fillable = [
        "title","icon","description"
    ];

    public function resources()
    {
        return $this->hasMany(Resource::class,"category_id");
    }
}

app/Http/Controllers/ResourceCategoryController.php
<?php

namespace App\Http\Controllers;

use App\ResourceCategory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class ResourceCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("resource_category.index")->withCategories(ResourceCategory::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("resource_category.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'icon' => 'required',
            'description' => 'required',
        ]);

        ResourceCategory::create($request->all());

        return $this->redirectToIndexForSuccess('New category has been added!');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(int $id)
    {
        $resourceCategory = ResourceCategory::find($id);

        if(null === $resourceCategory)
            return abort(404);

        return view("resource_category.edit")->withCategory($resourceCategory);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request,int $id)
    {
        $request->validate([
            'title' => 'required',
            'icon' => 'required',
            'description' => 'required',
        ]);

        ResourceCategory::findOrFail($id)
            ->fill($request->toArray())
            ->update();

        return $this->redirectToIndexForSuccess('Your category has been updated.');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(int $id)
    {
        ResourceCategory::findOrFail($id)->delete();

        return $this->redirectToIndexForSuccess('Your category has been deleted.');
    }

    /**
     * Returns a consistent redirect response for a successful action.
     * @param string $message
     * @return \Illuminate\Http\RedirectResponse
     */
    private function redirectToIndexForSuccess(string $message): RedirectResponse
    {
        return Redirect::to(route('categories.index'))->with('success',$message);
    }
}

resources/views/resource_category/create.blade.php
@extends('layouts/app')

@section('title','Add Category')

@section('content')
    <h1>Add a new category</h1>


    @if ($errors->any())
        <div class="alert alert-danger">
            There was a problem adding this category.
        </div>
    @endif

    <form action="{{ route("categories.store") }}" method="POST">
        {{ csrf_field() }}

        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" class="form-control @error('title')is-invalid"@enderror" id="title"
            placeholder="" required>
            @error('title')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>

        <div class="form-group">
            <label for="icon">Icon</label>
            <input type="text" name="icon" class="form-control @error('icon')is-invalid"@enderror" id="icon"
            placeholder="loading" required>
            @error('icon')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>
        <div class="form-group">
            <label class="form-check-label" for="description">Description</label>
            <textarea class="form-control @error('description')is-invalid" @enderror rows="5" name="description"
                      id="description"></textarea>
            @error('description')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/resource_category/edit.blade.php
@extends('layouts/app')

@section('title','Edit Category')

@section('content')
    <h1>Editing a category</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            There was a problem adding this category.
        </div>
    @endif

    <form action="{{ route("categories.update", $category->id) }}" method="POST">
        {{ csrf_field() }}
        @method("PATCH")

        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" value="{{ $category->title }}" name="title"
                   class="form-control @error('title')is-invalid"@enderror" id="title"
            placeholder="" required>
            @error('title')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>

        <div class="form-group">
            <label for="icon">Icon</label>
            <input type="text" value="{{ $category->icon }}" name="icon"
                   class="form-control @error('icon')is-invalid"@enderror" id="icon"
            placeholder="loading" required>
            @error('icon')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>
        <div class="form-group">
            <label class="form-check-label" for="description">Description</label>
            <textarea class="form-control @error('description')is-invalid" @enderror rows="5" name="description"
                      id="description">{{ $category->description }}</textarea>
            @error('description')
            <div class="invalid-feedback">{{ $message }}</div>@enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/resource_category/index.blade.php
@extends('layouts/app')
@section('title','Categories')

@section('content')
    <h1>Categories</h1>
    <hr/>

    @if(session("success"))
        <p class="alert alert-success">{{ session("success") }} <a href="#" class="close" data-dismiss="alert"
                                                                   aria-label="close">&times;</a></p>
    @endif

    <a href="{{ route("categories.create") }}" class="btn btn-primary mb-3">Add Category</a>
    <div class="table-responsive">
        <table class="table">
            <tr class="thead-light">
                <th>Title</th>
                <th>Icon</th>
                <th>Description</th>
                <th>Options</th>
            </tr>
            @foreach($categories as $category)
                <tr>
                    <td>{{ $category->title }}</td>
                    <td style="font-family: 'Material Icons',serif;">{{ $category->icon }}</td>
                    <td>{{ $category->description }}</td>
                    <td class="d-flex">
                        <a href="{{ route("categories.resources.index",$category->id) }}"
                           class="btn btn-outline-primary mr-2">Resources</a>

                        <a href="{{ route("categories.edit",$category->id) }}"
                           class="btn btn-outline-primary mr-2">Edit</a>

                        <form action="{{ route("categories.destroy",$category->id) }}" method="POST">
                            {{ csrf_field() }}
                            @method('DELETE')
                            <button class="btn btn-outline-danger" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection